### ISSUE TITLE
[FEATURE REQUEST] plugin for GCP (cloud storage)

### ISSUE THREAD

**Issue by tsuyoshiwada** [reg-viz/reg-suit#113]
Hi, Thank you for creating great tools :dog: !!

I'd like to use GCP (cloud storage) instead of AWS S3 when using `reg-suit`.
Is there a possibility to develop a plug-in for `cloud storage` in the future :smiley: ??

**Comment by Quramy** [comment]
It looks cool! And I’ve planned GCS feature(FYI see #1

But, I’m not good at GCS sdk...  

If you would not mind, please show me the following code snipets?

- How to push image files to GCS with Node.js
- How to tell GCS credentials information to users’ CI service safely. ( env value or something like .aws/credential file or...

**Comment by tsuyoshiwada** [comment]
@Quramy Thanks for the response!

Just like you, I'm not familiar with GCS (and GCP) either :sob:
However, I actually want to use `reg-suit` using GCS.

Therefore, I will try to show code snippets so I'm glad if you can wait for a while :wink:

**Comment by Quramy** [comment]
@tsuyoshiwada I've just published https://www.npmjs.com/package/reg-publish-gcs-plugin. Pls check it out and send me some FBs 👋 .

**Comment by tsuyoshiwada** [comment]
Thank you very much!! So fast work... :joy:
When actually using it, I will give feedback :pray:
