### ISSUE TITLE
Gitlab Support

### ISSUE THREAD

**Issue by frosato-ekino** [reg-viz/reg-suit#118]
Hi guys, 
First of all thank you for this very good tool suits !
Any plan for supporting Gitlab by providing a Gitlab equivalent of `reg-notify-github-plugin`?
I would be please to participate if you need a hand.

**Comment by Quramy** [comment]
Thanks :)

I want to a gitlab plugin too(Now I use self-hosted GitLab in my work).

**Comment by Quramy** [comment]
@frosato-ekino I've just published https://www.npmjs.com/package/reg-notify-gitlab-plugin 🎉
Please check it out and send me some FBs if you don't mind.

FYI: I've created sample GitLab project using this plugin https://gitlab.com/Quramy/reg-puppeteer-demo/merge_requests/1#note_86711598 .
