### ISSUE TITLE
reg-notify-gitlab-plugin - report display is broken

### ISSUE THREAD

**Issue by frosato-ekino** [reg-viz/reg-suit#123]
Missing space after smiley mess the render of the markdown
`:white_cirle::white_cirle:` -> `:white_cirle:<SPACE>:white_cirle:`

![capture d ecran 2018-07-09 a 09 40 21](https://user-images.githubusercontent.com/31624379/42437087-3d3dd770-835c-11e8-870e-d04f55d2b8d0.png)

Pull request: https://github.com/reg-viz/reg-suit/pull/121

**Comment by Quramy** [comment]
Thanks! I’ve published your fixes as v0.7.9 :)
