### ISSUE TITLE
Image url should be encoded

### ISSUE THREAD

**Issue by frosato-dev** [reg-viz/reg-suit#124]
I have some fancy stories names that include special characters (eg: `+`),
In the index.html, the load of the image fails (404 errors) because of wrong URI encoding.

https://<SOMETHING>.s3.amazonaws.com/<SHA>/actual/<FANCY_NAME_WITH_SPECIAL_CHARS>.png

I saw that in the generated index files we have `raw` and `encoded` values. the encoded should be used.

Step to reproduce: name a story something like `Foo+I/Bar`

**Comment by Quramy** [comment]
Hmmm, I think it might be reg-cli’s problem :thinking:. @bokuweb How about this ?

**Comment by bokuweb** [comment]
@frosato-ekino Thanks for your report :) It is `reg-cli` (https://github.com/reg-viz/reg-cli) 's issue. I'll do some investigation.

**Comment by bokuweb** [comment]
@frosato-ekino I fixed this issue, could you please try the latest version if you get a chance?

**Comment by frosato-ekino** [comment]
I have renamed my stories to silent the bug but I'll try to reproduce and let you know.
