### ISSUE TITLE
[SOLVED] How to configure `reg-publish-gcs-plugin`  

### ISSUE THREAD

**Issue by elchiconube** [reg-viz/reg-suit#160]
I want to use `reg-publish-gcs-plugin` but I cannot see any step in the documentation. Please, can you update the documentation with a few steps. Thanks

**Comment by elchiconube** [comment]
1. Create a JSON file with credentials here: https://console.cloud.google.com/apis/credentials/serviceaccountkey
2. Save it here:
 - On Windows, this is `%APPDATA%/gcloud/application_default_credentials.json`
 - On other systems, `$HOME/.config/gcloud/application_default_credentials.json`

**Comment by Quramy** [comment]
Hi, I'm grad your problem has been solved 😄 
It seems that your problem was related to configuring GCP on your local machine.
