### ISSUE TITLE
`reg-suit init` raises an error when copying sample images

### ISSUE THREAD

**Issue by zaki-yama** [reg-viz/reg-suit#163]
## Describe the bug

When I run `reg-suit init`, an error occurs if I answer "Yes" to the last question, `Copy sample images to working dir`

```
$ ./node_modules/.bin/reg-suit init                                                                                                                        (git)-[reg-suit]
[reg-suit] info version: 0.8.2

...


? Copy sample images to working dir Yes
[reg-suit] info Initialization ended successfully ✨
{ NestedError: cannot stat path `/Users/yamazaki/repos/github.com/zaki-yama/react-lightning-design-system/node_modules/reg-cli/report/sample/actual/sample.png`: ENOENT: no such file or directory, stat '/Users/yamazaki/repos/github.com/zaki-yama/react-lightning-design-system/node_modules/reg-cli/report/sample/actual/sample.png'
    at fsP.stat.catch.err (/Users/yamazaki/repos/github.com/zaki-yama/react-lightning-design-system/node_modules/cp-file/fs.js:29:8)
Caused By: Error: ENOENT: no such file or directory, stat '/Users/yamazaki/repos/github.com/zaki-yama/react-lightning-design-system/node_modules/reg-cli/report/sample/actual/sample.png'
  nested:
   { Error: ENOENT: no such file or directory, stat '/Users/yamazaki/repos/github.com/zaki-yama/react-lightning-design-system/node_modules/reg-cli/report/sample/actual/sample.png'
     errno: -2,
     code: 'ENOENT',
     syscall: 'stat',
     path:
      '/Users/yamazaki/repos/github.com/zaki-yama/react-lightning-design-system/node_modules/reg-cli/report/sample/actual/sample.png' },
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   '/Users/yamazaki/repos/github.com/zaki-yama/react-lightning-design-system/node_modules/reg-cli/report/sample/actual/sample.png',
  name: 'CpFileError' }
```

## Reproduced step

1. `npm install reg-suit`
2. `./node_modules/.bin/reg-suit init`
3. Follow the prompt until the last question, `Copy sample images to working dir`
4. Answer "Yes"

## Expected behavior

Maybe successfully finishes coping sample images.

## Actual behavior

The error I pasted above occured.

## Screenshots

![SS 2019-10-28 1 23 09](https://user-images.githubusercontent.com/1001444/67637807-88733780-f921-11e9-96de-5e71a1218db2.png)

---

It might be because `reg-cli` doesn't publish `report/sample` directory.
(I guessed from here: https://github.com/reg-viz/reg-cli/blob/master/package.json#L77-L85)

**Comment by bokuweb** [comment]
@zaki-yama Thanks for your report :) I fixed the bug with https://github.com/reg-viz/reg-suit/pull/164.
Could you please try latest version.

**Comment by zaki-yama** [comment]
@bokuweb 
Thank you!
I tried the latest version (`0.8.6`), and that generated an empty (0 byte) `sample.png`.
Is it expected behavior?
The output directory is the default `directory_contains_actual_images`.

Environment:
- OS: Mac Mojave 10.14.6
- Node: v10.15.3
- npm: v6.4.1

**Comment by bokuweb** [comment]
@zaki-yama oops. Sorry, I'll do some investigation about it...
