### ISSUE TITLE
[Question] How to make the CI test "fail" ?

### ISSUE THREAD

**Issue by rborn** [reg-viz/reg-suit#259]
I manage to setup everything and it works great - thank you for building this 😻 -  but I don't manage to get the result of the test and  make the pipeline fail in a CI environment

Any idea?

Thank you

**Comment by Quramy** [comment]
You can check if there're differences with the following shell script :)

```sh
test $(node -e "console.log(require('./.reg/out.json').diffItems.length)") -eq 0
```

**Comment by rborn** [comment]
@Quramy  That did it, thanks a lot 😻
