### ISSUE TITLE
create a limit to show  🔵 emoji to bot comment

### ISSUE THREAD

**Issue by ostk0069** [reg-viz/reg-suit#566]
## Is your feature request related to a problem? Please describe.

In my project, we have many stories to regress testing. I think there are more than 4000.

This means that I have to scroll more than 4000 🔵 emoji when there are any diffs in project.

## Describe the solution you'd like

make a limit number to show 🔵 and show how much more to show with number

eg: 

now: 

```
Check this report, and review them.
🔴 🔴 🔴 🔴 
⚪ ⚪ ⚪ ⚪ ⚪ 
🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 
```

request: 
```
Check this report, and review them.
🔴 🔴 🔴 🔴 
⚪ ⚪ ⚪ ⚪ ⚪ 
🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 🔵 ... and 4 more
```

if there's any other suggestion which solve this problem, looks okay for me.

**Comment by samturrell** [comment]
On a similar note, it would be great if we could set the `shortDescription` manually on the [reg-notify-github-plugin config](https://github.com/reg-viz/reg-suit/blob/master/packages/reg-notify-github-plugin/README.md) for when projects reach a certain size, like the [reg-notify-github-with-api-plugin allows](https://github.com/reg-viz/reg-suit/blob/master/packages/reg-notify-github-with-api-plugin/README.md#configure)
