### ISSUE TITLE
Cannot access page to get cliientID for reg-notify-github-plugin 

### ISSUE THREAD

**Issue by m-kikuchi777** [reg-viz/reg-suit#577]
## Describe the bug

I installed reg-suit Github app. 
But, When I access to `https://reg-viz.github.io/gh-app/` showing 404.
Do I need to do anything other than installing Github app?

## Reproduced step

1. Install Github app. https://github.com/apps/reg-suit
2. Go to https://reg-viz.github.io/gh-app/
3. Show 404 page.

## Expected behavior

I can access https://reg-viz.github.io/gh-app/ and get the ClientID.

## Actual behavior

404 was shown.

## Screenshots

![image](https://user-images.githubusercontent.com/45266786/156693785-09793833-867b-4e26-bb03-882a105af080.png)

**Comment by Quramy** [comment]
Ooops, I'll investigate this!

**Comment by Quramy** [comment]
@m-kikuchi777 For now pls use https://github.com/login/oauth/authorize?client_id=Iv1.88b2ad3983e01d13

**Comment by m-kikuchi777** [comment]
Thanks for the quick response and investigate!
I was able to get the ClientID.

**Comment by Quramy** [comment]
I've fixed this. Thanks for reporting
