### ISSUE TITLE
[reg-publish-s3-plugin] use @aws-sdk/client-s3 instead of aws-sdk

### ISSUE THREAD

**Issue by yizumi1012xxx** [reg-viz/reg-suit#622]
## Is your feature request related to a problem? Please describe.

I would like you to use @aws-sdk/client-s3 instead of aws-sdk in reg-publish-s3-plugin.

## Describe the solution you'd like

update aws-sdk.

## Describe alternatives you've considered

nothing.

## Additional context

If there are no concerns, I will address them.

**Comment by heavenshell** [comment]
We are also facing the same warning in our project.

```
(node:4641) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) 
into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
```
